"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path


# ==========================================================
# RUTAS DEL PROYECTO
# ==========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================================================
# SEGURIDAD
# ==========================================================
#
# SECRET_KEY se toma de la variable de entorno DJANGO_SECRET_KEY
# en producción. El valor "django-insecure-..." solo se usa como
# respaldo para desarrollo local y NUNCA debe usarse en un
# entorno real: cualquiera con este código podría forjar
# sesiones, tokens de reseteo de contraseña y firmas.
#
# DEBUG, ALLOWED_HOSTS y las banderas SECURE_*/SESSION_*/CSRF_*
# de más abajo dependen de la infraestructura real (dominio,
# si TLS se termina en un proxy, etc.), así que se activan por
# variable de entorno en vez de forzarse aquí — hacerlo a
# ciegas rompería `manage.py runserver` en desarrollo.
#
# ==========================================================

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-)e4t9-69@ib29ztry+0_'
    'fz6ru-=snb4b0)ynx+wtkj^(c9n0ng',
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]

if not DEBUG:
    # Solo se activan bajo HTTPS real; en desarrollo (DEBUG=True)
    # forzarlas rompería el servidor local por HTTP.
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ==========================================================
# APLICACIONES
# ==========================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Django REST Framework
    'rest_framework',
    'rest_framework.authtoken',

    # Aplicaciones SIGTA
    'usuarios',
    'soporte',
    'auditoria',
    'mantenimiento',
    'compras',
    'recuperacion',
]


# ==========================================================
# MIDDLEWARE
# ==========================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'usuarios.middleware.CambioPasswordObligatorioMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==========================================================
# URLS
# ==========================================================

ROOT_URLCONF = 'config.urls'


# ==========================================================
# TEMPLATES
# ==========================================================

TEMPLATES = [
    {
        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ==========================================================
# WSGI
# ==========================================================

WSGI_APPLICATION = 'config.wsgi.application'


# ==========================================================
# BASE DE DATOS
# ==========================================================

DATABASES = {
    'default': {
        'ENGINE':
            'django.db.backends.sqlite3',

        'NAME':
            BASE_DIR / 'db.sqlite3',
    }
}


# ==========================================================
# HASH DE CONTRASEÑAS
# ==========================================================
#
# Argon2id (ganador del Password Hashing Competition, y el
# algoritmo que Django recomienda como más fuerte) queda como
# hasher principal. Se conservan los hashers PBKDF2 solo para
# poder seguir leyendo/verificando contraseñas ya existentes
# en la base de datos; cualquier login exitoso las re-encripta
# automáticamente con Argon2id (comportamiento estándar de
# Django: check_password migra el hash al hasher preferido).
#
# ==========================================================

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]


# ==========================================================
# VALIDACIÓN DE CONTRASEÑAS
# ==========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator',
    },

    {
        'NAME':
            'usuarios.validators.ComplejidadPasswordValidator',
    },
]


# ==========================================================
# SESIÓN Y FUERZA BRUTA
# ==========================================================
#
# Umbrales usados por usuarios/views.py::login_view para el
# bloqueo temporal de cuentas (HU de seguridad). Centralizados
# aquí para no tener el número "mágico" repartido en el código.
#
# ==========================================================

LOGIN_MAX_INTENTOS_FALLIDOS = 5
LOGIN_MINUTOS_BLOQUEO = 15

# El token de DRF no expira por sí solo: se fuerza una vida
# máxima de sesión para reducir la ventana de un token robado.
SESION_TOKEN_HORAS_VALIDEZ = 12


# ==========================================================
# INTERNACIONALIZACIÓN
# ==========================================================

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# ==========================================================
# ARCHIVOS ESTÁTICOS
# ==========================================================

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==========================================================
# USUARIO PERSONALIZADO
# ==========================================================

AUTH_USER_MODEL = 'usuarios.Usuario'


# ==========================================================
# DJANGO REST FRAMEWORK
# ==========================================================

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'usuarios.authentication.ExpiringTokenAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# ==========================================================
# CORREO - DESARROLLO
# ==========================================================
#
# IMPORTANTE:
# Durante esta etapa el correo NO se enviará realmente.
#
# Django mostrará el mensaje y el código de recuperación
# directamente en la consola donde ejecutas:
#
# python manage.py runserver
#
# Después cambiaremos este MAILER por Outlook / Microsoft 365.
# ==========================================================

MAILERS = {

    'default': {

        'BACKEND':
            'django.core.mail.backends.console.EmailBackend',
    },
}