# Generated by Django 6.1 on 2026-08-12 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_area_rol_usuariorol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('es_inicial', models.BooleanField(default=False)),
                ('es_terminal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('equipo_afectado', models.CharField(blank=True, max_length=200)),
                ('diagnostico', models.TextField(blank=True)),
                ('solucion', models.TextField(blank=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.area')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soporte.categoriaticket')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soporte.estadoticket')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_solicitados', to=settings.AUTH_USER_MODEL)),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
