# Generated by Django 6.1 on 2026-08-13 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
        ('usuarios', '0002_area_rol_usuariorol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='codigo_compra_vinculada',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='componente_requerido',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='conformidad_usuario',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='criterio_tecnico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='especialistas_apoyo',
            field=models.ManyToManyField(blank=True, related_name='tickets_apoyo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='especificaciones_tecnicas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='evidencia',
            field=models.CharField(blank=True, help_text='Referencia o nombre del archivo de evidencia.', max_length=300),
        ),
        migrations.AddField(
            model_name='ticket',
            name='informe_final',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='observaciones_usuario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='plan_solucion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requiere_compra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resultado_pruebas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rework_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_problema',
            field=models.CharField(blank=True, choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('RED', 'Redes y conectividad'), ('PROYECTOR', 'Proyectores'), ('SISTEMA', 'Sistema institucional'), ('ACCESO', 'Accesos y cuentas'), ('OTRO', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='categoriaticket',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='estadoticket',
            name='codigo',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_soporte', to='usuarios.area'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='equipo_afectado',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ubicacion',
            field=models.CharField(max_length=200),
        ),
    ]
