# Generated by Django 6.1 on 2026-08-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_ticket_cerrado_en_ticket_codigo_compra_vinculada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10, null=True),
        ),
    ]
