# Generated by Django 6.1 on 2026-08-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0003_alter_ticket_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='evidencia_archivo',
            field=models.FileField(blank=True, help_text='Imagen o documento adjunto como evidencia.', null=True, upload_to='soporte/evidencias/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='soporte.categoriaticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='soporte.estadoticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='evidencia',
            field=models.TextField(blank=True, default='', help_text='Descripción adicional de la evidencia.'),
        ),
    ]
