# Generated by Django 6.1 on 2026-08-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0004_ticket_evidencia_archivo_alter_ticket_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asignado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se designó al especialista.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='clasificado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se clasificó prioridad y SLA.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='conformidad_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el solicitante informó conformidad.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='inicio_atencion_en',
            field=models.DateTimeField(blank=True, help_text='Fecha de inicio de la atención técnica.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pruebas_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se registraron las pruebas técnicas.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_cumplido',
            field=models.BooleanField(blank=True, help_text='Indica si el ticket fue resuelto dentro del SLA establecido.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_fecha_limite',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora límite de atención según SLA.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de horas asignadas para el SLA.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='validado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que UTIC recibió y validó el ticket.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='verificado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha de verificación del funcionamiento.', null=True),
        ),
    ]
