# Generated by Django 6.1 on 2026-08-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0006_seed_estados_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estado_compra_componente',
            field=models.CharField(blank=True, choices=[('SOLICITADA', 'Solicitada'), ('NO_VIABLE', 'No viable'), ('VIABLE', 'Viable')], max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='motivo_no_viable',
            field=models.TextField(blank=True),
        ),
    ]
