# Generated by Django 5.2.17 on 2026-09-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0008_seed_estado_cerrado_sin_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='componente_entregado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que Almacén despachó el componente y el especialista pudo retomar la atención del ticket.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cotizacion_archivo',
            field=models.FileField(blank=True, help_text='Cotización o proforma del componente requerido.', null=True, upload_to='soporte/cotizaciones/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='informe_tecnico',
            field=models.TextField(blank=True, help_text='Descargo técnico que el especialista dirige a la jefatura al terminar la reparación y las pruebas.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado_compra_componente',
            field=models.CharField(blank=True, choices=[('SOLICITADA', 'Solicitada'), ('NO_VIABLE', 'No viable'), ('VIABLE', 'Viable'), ('ENTREGADA', 'Componente entregado')], max_length=20),
        ),
    ]
