# Generated by Django 5.2.17 on 2026-09-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0009_informe_tecnico_y_entrega_componente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='informe_elevado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que la jefatura elevó el informe final de actividades a la Dirección.', null=True),
        ),
    ]
