# Generated by Django 5.2.17 on 2026-09-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0010_elevacion_informe_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='informe_recibido_director_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el Director recibió el informe de actividades.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='informe_recibido_jefe_carrera_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el Jefe de carrera recibió el informe de actividades.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='proceso_finalizado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que ambos destinatarios acusaron recibo del informe y el proceso llegó a su evento final.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='informe_elevado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que la jefatura elevó el informe final de actividades a sus destinatarios.', null=True),
        ),
    ]
