# Generated by Django 5.2.17 on 2026-09-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0011_distribucion_informe_actividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='referencia_ubicacion',
            field=models.CharField(blank=True, default='', help_text='Referencias para llegar al ambiente: bloque, piso o punto cercano conocido.', max_length=200),
        ),
    ]
