# Generated by Django 5.2.17 on 2026-09-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0012_referencia_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='informe_recibido_jefe_carrera_en',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='proceso_finalizado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que la Dirección acusó recibo del informe y el proceso llegó a su evento final.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ubicacion',
            field=models.CharField(help_text='Aula o ambiente donde se presenta el problema (por ejemplo: Aula C0-07, Laboratorio de Redes).', max_length=200),
        ),
    ]
