# Generated by Django 6.1 on 2026-09-04 21:13

from django.db import migrations, models


def crear_estado_en_diagnostico(apps, schema_editor):
    EstadoTicket = apps.get_model('soporte', 'EstadoTicket')
    EstadoTicket.objects.get_or_create(
        codigo='EN_DIAGNOSTICO',
        defaults={
            'nombre': 'En diagnóstico',
            'descripcion': 'Orden recibida por el especialista y pendiente de diagnóstico.',
            'es_inicial': False,
            'es_terminal': False,
            'activo': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0013_informe_solo_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='acciones_realizadas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cantidad_componente',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='componentes_utilizados',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='evidencia_diagnostico',
            field=models.FileField(blank=True, null=True, upload_to='soporte/diagnosticos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='evidencia_intervencion',
            field=models.FileField(blank=True, null=True, upload_to='soporte/intervenciones/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='evidencia_pruebas',
            field=models.FileField(blank=True, null=True, upload_to='soporte/pruebas/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='justificacion_compra',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='observaciones_diagnostico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='proveedor_cotizacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado_compra_componente',
            field=models.CharField(blank=True, choices=[('BORRADOR', 'Borrador'), ('SOLICITADA', 'Solicitada'), ('NO_VIABLE', 'No viable'), ('VIABLE', 'Viable'), ('ENTREGADA', 'Componente entregado')], max_length=20),
        ),
        migrations.RunPython(crear_estado_en_diagnostico, migrations.RunPython.noop),
    ]
