# Generated by Django 6.1 on 2026-08-23 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_permiso_alter_usuariorol_options_alter_area_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('es_inicial', models.BooleanField(default=False)),
                ('es_terminal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequerimientoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], max_length=20)),
                ('evidencia', models.TextField(blank=True, default='', help_text='Descripción adicional o referencia de la evidencia.')),
                ('evidencia_archivo', models.FileField(blank=True, help_text='Imagen o documento cargado como evidencia.', null=True, upload_to='mantenimiento/evidencias/%Y/%m/')),
                ('requiere_reposicion', models.BooleanField(blank=True, null=True)),
                ('producto_requerido', models.CharField(blank=True, max_length=200)),
                ('cantidad_requerida', models.PositiveIntegerField(blank=True, null=True)),
                ('especificacion_producto', models.TextField(blank=True)),
                ('producto_disponible_almacen', models.BooleanField(blank=True, null=True)),
                ('producto_entregado', models.BooleanField(default=False)),
                ('observacion_almacen', models.TextField(blank=True)),
                ('derivado_compra', models.BooleanField(default=False)),
                ('codigo_compra_vinculada', models.CharField(blank=True, max_length=30)),
                ('compra_completada', models.BooleanField(default=False)),
                ('trabajo_realizado', models.TextField(blank=True)),
                ('observaciones_trabajo', models.TextField(blank=True)),
                ('informe_trabajo', models.TextField(blank=True)),
                ('fotografia_trabajo', models.FileField(blank=True, help_text='Fotografía del trabajo de mantenimiento realizado.', null=True, upload_to='mantenimiento/trabajos/%Y/%m/')),
                ('recibido_en', models.DateTimeField(blank=True, null=True)),
                ('derivado_en', models.DateTimeField(blank=True, null=True)),
                ('revision_almacen_en', models.DateTimeField(blank=True, null=True)),
                ('inicio_mantenimiento_en', models.DateTimeField(blank=True, null=True)),
                ('informe_registrado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_mantenimiento', to='usuarios.area')),
                ('auxiliar_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_asignados', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to='mantenimiento.estadomantenimiento')),
                ('responsable_servicios_generales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_servicios_generales', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
