# Generated by Django 5.2.17 on 2026-09-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_prioridad_jefatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='clasificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='conformidad_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='costo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='cotizacion_archivo',
            field=models.FileField(blank=True, null=True, upload_to='mantenimiento/cotizaciones/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='diagnosticado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='diagnostico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='estado_compra_componente',
            field=models.CharField(blank=True, choices=[('SOLICITADA', 'Solicitada'), ('NO_VIABLE', 'No viable'), ('VIABLE', 'Viable'), ('ENTREGADA', 'Componente entregado')], max_length=20),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='informe_elevado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='informe_final',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='informe_recibido_director_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='motivo_no_viable',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='motivo_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='plan_solucion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='proceso_finalizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='pruebas_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='resultado_pruebas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='rework_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='validado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimientomantenimiento',
            name='verificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
