# Generated by Django 6.1 on 2026-08-23 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_area_rol_usuariorol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('modulo', models.CharField(choices=[('GENERAL', 'General'), ('SOPORTE', 'Soporte Técnico'), ('MANTENIMIENTO', 'Mantenimiento'), ('COMPRAS', 'Compras'), ('ADMINISTRACION', 'Administración'), ('AUDITORIA', 'Auditoría'), ('CONFIGURACION', 'Configuración'), ('AUTOSERVICIO', 'Portal Solicitante')], default='GENERAL', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['modulo', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='usuariorol',
            options={'verbose_name': 'Rol del usuario', 'verbose_name_plural': 'Roles de los usuarios'},
        ),
        migrations.AlterField(
            model_name='area',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_roles', to='usuarios.area'),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_asignados', to='usuarios.rol'),
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_asignados', to='usuarios.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asignados', to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'Permiso del rol',
                'verbose_name_plural': 'Permisos de los roles',
                'constraints': [models.UniqueConstraint(fields=('rol', 'permiso'), name='unique_rol_permiso')],
            },
        ),
    ]
