# Generated by Django 6.1 on 2026-08-26 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_permiso_alter_usuariorol_options_alter_area_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegacionAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_desde', models.DateTimeField()),
                ('vigencia_hasta', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('delegado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('delegante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegaciones_otorgadas', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegaciones', to='usuarios.rol')),
            ],
        ),
    ]
