# Generated by Django 6.1 on 2026-08-13 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_area_rol_usuariorol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('BIEN', 'Bien'), ('SERVICIO', 'Servicio'), ('ACTIVO_FIJO', 'Activo fijo'), ('COMPONENTE', 'Componente')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('especificaciones', models.TextField()),
                ('justificacion', models.TextField()),
                ('centro_costo', models.CharField(blank=True, max_length=100)),
                ('monto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('via_adquisicion', models.CharField(choices=[('PENDIENTE', 'Pendiente de evaluación'), ('CAJA_CHICA', 'Caja Chica'), ('FINANZAS', 'Finanzas')], default='PENDIENTE', max_length=20)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_COTIZACION', 'En cotización'), ('EN_APROBACION', 'En aprobación'), ('APROBADO', 'Aprobado'), ('ORDEN_EMITIDA', 'Orden emitida'), ('EN_TRANSITO', 'En tránsito'), ('RECIBIDO', 'Recibido'), ('EN_VERIFICACION', 'En verificación'), ('CERRADO', 'Cerrado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='NUEVO', max_length=30)),
                ('ticket_soporte_vinculado', models.CharField(blank=True, max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_compra', to='usuarios.area')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
