# Generated by Django 6.1 on 2026-08-26 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_flujo_caja_chica'),
        ('mantenimiento', '0001_initial'),
        ('soporte', '0005_ticket_asignado_en_ticket_clasificado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='componente_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fecha_despacho_almacen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fecha_ingreso_almacen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='observacion_verificacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='origen_modulo',
            field=models.CharField(choices=[('DIRECTA', 'Solicitud directa'), ('MANTENIMIENTO', 'Derivada de Mantenimiento'), ('SOPORTE', 'Derivada de Soporte Técnico')], default='DIRECTA', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='requerimiento_mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_generadas', to='mantenimiento.requerimientomantenimiento'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='ticket_soporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_generadas', to='soporte.ticket'),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='estado',
            field=models.CharField(choices=[('CREADO_PENDIENTE_DAF', 'Creado - pendiente DAF'), ('EVALUADO_PENDIENTE_CERTIFICACION', 'Evaluado - pendiente de certificación'), ('CERTIFICADO_PENDIENTE_VERIFICACION', 'Certificado - pendiente de verificación'), ('VERIFICADO_PENDIENTE_AUTORIZACION', 'Verificado - pendiente de autorización'), ('APROBADO_PARA_DESEMBOLSO', 'Aprobado para desembolso'), ('FONDOS_DESEMBOLSADOS', 'Fondos desembolsados'), ('COMPRA_REGISTRADA', 'Compra realizada - pendiente de entrega'), ('COMPRADO_Y_ENTREGADO', 'Comprado y entregado'), ('DESCARGO_PENDIENTE_LIQUIDACION', 'Descargo pendiente de liquidación'), ('CERRADO_ARCHIVADO', 'Cerrado y archivado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='CREADO_PENDIENTE_DAF', max_length=50),
        ),
    ]
