# Generated by Django 5.2.17 on 2026-09-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_retirar_verificacion_tesoreria'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='acta_firmada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fecha_entrega_solicitante',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='solicitud_recibida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='estado',
            field=models.CharField(choices=[('CREADO_PENDIENTE_DAF', 'Creado - pendiente DAF'), ('EVALUADO_PENDIENTE_CERTIFICACION', 'Evaluado - pendiente de certificación'), ('VERIFICADO_PENDIENTE_AUTORIZACION', 'Certificado - pendiente de autorización'), ('APROBADO_PARA_DESEMBOLSO', 'Aprobado para desembolso'), ('FONDOS_DESEMBOLSADOS', 'Fondos desembolsados'), ('COMPRA_REGISTRADA', 'Compra realizada - pendiente de entrega'), ('COMPRADO_Y_ENTREGADO', 'Comprado y entregado'), ('DESCARGO_PENDIENTE_LIQUIDACION', 'Acta firmada - pendiente de recepción'), ('CERRADO_ARCHIVADO', 'Cerrado y archivado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='CREADO_PENDIENTE_DAF', max_length=50),
        ),
    ]
