# Generated by Django 5.2.17 on 2026-09-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_entrega_con_acta_y_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='cantidad_entregada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='comprobante_compra',
            field=models.FileField(blank=True, help_text='Factura o recibo que respalda la compra realizada.', null=True, upload_to='compras/comprobantes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='entregado_a',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fecha_compra',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='observacion_ingreso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='observacion_salida',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='responsable_recepcion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
