# Generated by Django 5.2.17 on 2026-09-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_registro_control_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='fondos_recibidos_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fondos_recibidos_por',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='gestion_actualizada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='gestion_estado',
            field=models.CharField(blank=True, choices=[('BUSCANDO', 'Buscando producto o proveedor'), ('COMPRANDO', 'Compra en curso')], max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='gestion_nota',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
