# Generated by Django 6.1 on 2026-09-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_recepcion_fondos_y_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='comprobante_desembolso',
            field=models.FileField(blank=True, null=True, upload_to='compras/comprobantes/'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='tipo_desembolso',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
