# Generated by Django 6.1 on 2026-08-13 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=150)),
                ('modulo', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('SECURITY', 'Seguridad'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Correo institucional', max_length=100)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('puerto', models.PositiveIntegerField(default=587)),
                ('usuario', models.EmailField(blank=True, max_length=254)),
                ('remitente', models.EmailField(blank=True, max_length=254)),
                ('usar_tls', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='SIGTA', max_length=100)),
                ('institucion', models.CharField(default='Escuela Militar de Ingeniería', max_length=200)),
                ('unidad_academica', models.CharField(default='Unidad Académica Santa Cruz', max_length=200)),
                ('prefijo_soporte', models.CharField(default='SOP', max_length=10)),
                ('prefijo_compras', models.CharField(default='CMP', max_length=10)),
                ('limite_caja_chica', models.DecimalField(decimal_places=2, default=1500, max_digits=12)),
                ('intentos_login', models.PositiveIntegerField(default=5)),
                ('tiempo_bloqueo_minutos', models.PositiveIntegerField(default=15)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
